



extension WalletService {
	static let _walletHybridNftNltAssets: [any WalletAsset] = [
		NonLiquidAsset(id: AssetIdentifier(id: "511"), name: "Ethereum 2.0 Staking", description: "Ethereum 2.0 Staking", balance: BaseUnit(amount: 5, symbol: "ETH2", decimals: 18), stubPricePerUnit: 13),
		NonLiquidAsset(id: AssetIdentifier(id: "512"), name: "Cardano Staking", description: "Cardano Staking", balance: BaseUnit(amount: 100000, symbol: "ADA", decimals: 6), stubPricePerUnit: 24),
		NonLiquidAsset(id: AssetIdentifier(id: "513"), name: "Ethereum 2.0 Staking", description: "Ethereum 2.0 Staking", balance: BaseUnit(amount: 5, symbol: "ETH2", decimals: 18), stubPricePerUnit: 13),
		NonLiquidAsset(id: AssetIdentifier(id: "514"), name: "Ethereum 2.0 Staking", description: "Ethereum 2.0 Staking", balance: BaseUnit(amount: 5, symbol: "ETH2", decimals: 18), stubPricePerUnit: 13),
		NonLiquidAsset(id: AssetIdentifier(id: "515"), name: "Cardano Staking", description: "Cardano Staking", balance: BaseUnit(amount: 100000, symbol: "ADA", decimals: 6), stubPricePerUnit: 24),
		NonFungibleToken(id: AssetIdentifier(id: "6"), name: "CryptoPunk", balance: BaseUnit(amount: 1, symbol: "CryptoPunk", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "37"), name: "Imaginary Art", balance: BaseUnit(amount: 1, symbol: "IMA", decimals: 0)),
	]
	
	static let _walletHybridAssets: [any WalletAsset] = [
		FungibleToken(
			id: AssetIdentifier(id: "000"),
			name: "Toncoin",
			symbol: "TON",
			balance: BaseUnit(amount: 4343103000000,
							  symbol: "TON",
							  decimals: 9),
			stubPricePerUnit: 2.34
		),
		FungibleToken(
			id: AssetIdentifier(id: "001"),
			name: "Toncoin",
			symbol: "TON",
			balance: BaseUnit(amount: 4343103000000,
							  symbol: "TON",
							  decimals: 9),
			stubPricePerUnit: 2.34
		),
		FungibleToken(
			id: AssetIdentifier(id: "002"),
			name: "Toncoin",
			symbol: "TON",
			balance: BaseUnit(amount: 4343103000000,
							  symbol: "TON",
							  decimals: 9),
			stubPricePerUnit: 2.34
		),
		FungibleToken(
			id: AssetIdentifier(id: "003"),
			name: "Toncoin",
			symbol: "TON",
			balance: BaseUnit(amount: 4343103000000,
							  symbol: "TON",
							  decimals: 9),
			stubPricePerUnit: 2.34
		),
		NonLiquidAsset(id: AssetIdentifier(id: "511"), name: "Ethereum 2.0 Staking", description: "Ethereum 2.0 Staking", balance: BaseUnit(amount: 5, symbol: "ETH2", decimals: 18), stubPricePerUnit: 13),
		NonLiquidAsset(id: AssetIdentifier(id: "512"), name: "Cardano Staking", description: "Cardano Staking", balance: BaseUnit(amount: 100000, symbol: "ADA", decimals: 6), stubPricePerUnit: 24),
		NonLiquidAsset(id: AssetIdentifier(id: "513"), name: "Ethereum 2.0 Staking", description: "Ethereum 2.0 Staking", balance: BaseUnit(amount: 5, symbol: "ETH2", decimals: 18), stubPricePerUnit: 13),
		NonLiquidAsset(id: AssetIdentifier(id: "514"), name: "Ethereum 2.0 Staking", description: "Ethereum 2.0 Staking", balance: BaseUnit(amount: 5, symbol: "ETH2", decimals: 18), stubPricePerUnit: 13),
		NonLiquidAsset(id: AssetIdentifier(id: "515"), name: "Cardano Staking", description: "Cardano Staking", balance: BaseUnit(amount: 100000, symbol: "ADA", decimals: 6), stubPricePerUnit: 24),
		NonFungibleToken(id: AssetIdentifier(id: "6"), name: "CryptoPunk", balance: BaseUnit(amount: 1, symbol: "CryptoPunk", decimals: 0)),
	]
	
	static var _walletNonLiquidAssetsBuffer: [any WalletAsset] = [
		NonLiquidAsset(id: AssetIdentifier(id: "050001"), name: "Ethereum 2.0 Staking", description: "Ethereum 2.0 Staking", balance: BaseUnit(amount: 5, symbol: "ETH2", decimals: 18), stubPricePerUnit: 13),
		NonLiquidAsset(id: AssetIdentifier(id: "050002"), name: "Cardano Staking", description: "Cardano Staking", balance: BaseUnit(amount: 100000, symbol: "ADA", decimals: 6), stubPricePerUnit: 24),
		NonLiquidAsset(id: AssetIdentifier(id: "050003"), name: "Solana Staking", description: "Solana Staking", balance: BaseUnit(amount: 250000, symbol: "SOL", decimals: 9), stubPricePerUnit: 944),
		NonLiquidAsset(id: AssetIdentifier(id: "050004"), name: "Polkadot Staking", description: "Polkadot Staking", balance: BaseUnit(amount: 7500, symbol: "DOT", decimals: 10), stubPricePerUnit: 3),
		NonLiquidAsset(id: AssetIdentifier(id: "050005"), name: "Algorand Staking", description: "Algorand", balance: BaseUnit(amount: 500000, symbol: "ALGO", decimals: 6), stubPricePerUnit: 2),
		NonLiquidAsset(id: AssetIdentifier(id: "050006"), name: "ChainGPT Staking", description: "To The Moon", balance: BaseUnit(amount: 500000, symbol: "CGPTS", decimals: 6), stubPricePerUnit: 6),
		NonLiquidAsset(id: AssetIdentifier(id: "050007"), name: "Imaginary Staking", description: "Staking Imaginary Tokens", balance: BaseUnit(amount: 1000, symbol: "IMG", decimals: 18), stubPricePerUnit: 0.01),
		NonLiquidAsset(id: AssetIdentifier(id: "050008"), name: "Fictional Bond", description: "Fictional Token Bonds", balance: BaseUnit(amount: 500, symbol: "FICB", decimals: 6), stubPricePerUnit: 1000),
		NonLiquidAsset(id: AssetIdentifier(id: "050009"), name: "Imaginary Staking", description: "Imaginary Coin Staking", balance: BaseUnit(amount: 10000, symbol: "IMCS", decimals: 6), stubPricePerUnit: 0.02),
		NonLiquidAsset(id: AssetIdentifier(id: "050010"), name: "Fictional Savings", description: "Fiction Token Savings", balance: BaseUnit(amount: 2000, symbol: "FTKS", decimals: 4), stubPricePerUnit: 4),
		NonLiquidAsset(id: AssetIdentifier(id: "050011"), name: "Mythical Vault", description: "Mythical Dollar High Yield Vault", balance: BaseUnit(amount: 100000, symbol: "MYDV", decimals: 2), stubPricePerUnit: 1),
		NonLiquidAsset(id: AssetIdentifier(id: "050012"), name: "Startup Equity", description: "Startup Equity", balance: BaseUnit(amount: 100, symbol: "SE", decimals: 0), stubPricePerUnit: 600),
		NonLiquidAsset(id: AssetIdentifier(id: "050013"), name: "Private Company Shares", description: "Private Company Shares", balance: BaseUnit(amount: 200, symbol: "PCS", decimals: 0), stubPricePerUnit: 600),
		NonLiquidAsset(id: AssetIdentifier(id: "050014"), name: "Convertible Bonds", description: "Convertible Bonds", balance: BaseUnit(amount: 50, symbol: "CB", decimals: 0), stubPricePerUnit: 600),
		NonLiquidAsset(id: AssetIdentifier(id: "050015"), name: "Venture Capital Fund", description: "Venture Capital Fund", balance: BaseUnit(amount: 10, symbol: "VCF", decimals: 0), stubPricePerUnit: 10000),
		NonLiquidAsset(id: AssetIdentifier(id: "050016"), name: "Limited Partnership", description: "Limited Partnership", balance: BaseUnit(amount: 5, symbol: "LP", decimals: 0), stubPricePerUnit: 15000),
		NonLiquidAsset(id: AssetIdentifier(id: "050017"), name: "Hedge Fund", description: "Hedge Fund", balance: BaseUnit(amount: 8, symbol: "HF", decimals: 0), stubPricePerUnit: 10000),
		NonLiquidAsset(id: AssetIdentifier(id: "050018"), name: "Private Equity Fund", description: "Private Equity Fund", balance: BaseUnit(amount: 10, symbol: "PEF", decimals: 0), stubPricePerUnit: 9000),
		NonLiquidAsset(id: AssetIdentifier(id: "050019"), name: "Peer-to-Peer Lending", description: "Peer-to-Peer Lending", balance: BaseUnit(amount: 1000, symbol: "P2P", decimals: 0), stubPricePerUnit: 50),
		NonLiquidAsset(id: AssetIdentifier(id: "050020"), name: "Farm Land", description: "Farm Land", balance: BaseUnit(amount: 10, symbol: "FL", decimals: 0), stubPricePerUnit: 20000),
		NonLiquidAsset(id: AssetIdentifier(id: "050021"), name: "Mobile Home Park", description: "Mobile Home Park", balance: BaseUnit(amount: 5, symbol: "MHP", decimals: 0), stubPricePerUnit: 60000),
		NonLiquidAsset(id: AssetIdentifier(id: "050022"), name: "Self-Storage Facility", description: "Self-Storage Facility", balance: BaseUnit(amount: 2, symbol: "SSF", decimals: 0), stubPricePerUnit: 75000),
		NonLiquidAsset(id: AssetIdentifier(id: "050023"), name: "Apartment Complex", description: "Apartment Complex", balance: BaseUnit(amount: 1, symbol: "AC", decimals: 0), stubPricePerUnit: 500000),
		NonLiquidAsset(id: AssetIdentifier(id: "050024"), name: "Office Building", description: "Office Building", balance: BaseUnit(amount: 1, symbol: "OB", decimals: 0), stubPricePerUnit: 600000),
		NonLiquidAsset(id: AssetIdentifier(id: "050025"), name: "Shopping Center", description: "Shopping Center", balance: BaseUnit(amount: 1, symbol: "SC", decimals: 0), stubPricePerUnit: 5000),
	]
	static var _walletNftAssetsBuffer: [any WalletAsset] = [
		NonFungibleToken(id: AssetIdentifier(id: "060025"), name: "CryptoPunk", balance: BaseUnit(amount: 1, symbol: "CryptoPunk", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060026"), name: "Bored Ape Yacht Club", balance: BaseUnit(amount: 1, symbol: "BAYC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060027"), name: "World of Women", balance: BaseUnit(amount: 1, symbol: "WOW", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060028"), name: "Rumble Kong League", balance: BaseUnit(amount: 1, symbol: "RKL", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060029"), name: "Sevens", balance: BaseUnit(amount: 1, symbol: "Sevens", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060030"), name: "Imaginary Art", balance: BaseUnit(amount: 1, symbol: "IMGART", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060031"), name: "Imaginary Art", balance: BaseUnit(amount: 1, symbol: "IMA", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060032"), name: "Fictional Creatures", balance: BaseUnit(amount: 1, symbol: "FCR", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060033"), name: "Mythical Landscapes", balance: BaseUnit(amount: 1, symbol: "MLA", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060034"), name: "Fictional Character", balance: BaseUnit(amount: 1, symbol: "FICCHAR", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060035"), name: "Mythical Creature", balance: BaseUnit(amount: 1, symbol: "MYTHCRE", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060036"), name: "Fantasy Landscape", balance: BaseUnit(amount: 1, symbol: "FANLAND", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060037"), name: "Dream World", balance: BaseUnit(amount: 1, symbol: "DREAMW", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060038"), name: "Eights", balance: BaseUnit(amount: 1, symbol: "Eights", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060039"), name: "Cool Cats", balance: BaseUnit(amount: 1, symbol: "CC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060040"), name: "DegenApes", balance: BaseUnit(amount: 1, symbol: "DA", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060041"), name: "MetaHeroes", balance: BaseUnit(amount: 1, symbol: "MH", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060042"), name: "ArtBlocks", balance: BaseUnit(amount: 1, symbol: "AB", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060042"), name: "Mutant Ape Yacht Club", balance: BaseUnit(amount: 1, symbol: "MAYC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060043"), name: "Galaxy Eggs", balance: BaseUnit(amount: 1, symbol: "GE", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060044"), name: "Pudgy Penguins", balance: BaseUnit(amount: 1, symbol: "PP", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060045"), name: "PixelPandas", balance: BaseUnit(amount: 1, symbol: "PxP", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060046"), name: "CryptoCats", balance: BaseUnit(amount: 1, symbol: "CC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060047"), name: "CryptoDogs", balance: BaseUnit(amount: 1, symbol: "CD", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060048"), name: "AI-Generated Art", balance: BaseUnit(amount: 1, symbol: "AIA", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060049"), name: "DreamPunks", balance: BaseUnit(amount: 1, symbol: "DP", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060050"), name: "AstroBeasts", balance: BaseUnit(amount: 1, symbol: "AB", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060051"), name: "SuperMeebits", balance: BaseUnit(amount: 1, symbol: "SM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060052"), name: "CyberKongs", balance: BaseUnit(amount: 1, symbol: "CK", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060053"), name: "ZombieToads", balance: BaseUnit(amount: 1, symbol: "ZT", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060054"), name: "CosmicCows", balance: BaseUnit(amount: 1, symbol: "CC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060055"), name: "SpaceGiraffes", balance: BaseUnit(amount: 1, symbol: "SG", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060056"), name: "AlienCacti", balance: BaseUnit(amount: 1, symbol: "AC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060057"), name: "MysticMonkeys", balance: BaseUnit(amount: 1, symbol: "MM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060058"), name: "CryptoDoggos", balance: BaseUnit(amount: 1, symbol: "CD", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060059"), name: "PixelPortraits", balance: BaseUnit(amount: 1, symbol: "PP", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060060"), name: "DigitalDragons", balance: BaseUnit(amount: 1, symbol: "DD", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060061"), name: "GalacticGeckos", balance: BaseUnit(amount: 1, symbol: "GG", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060062"), name: "VirtualVikings", balance: BaseUnit(amount: 1, symbol: "VV", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060063"), name: "RoboRabbits", balance: BaseUnit(amount: 1, symbol: "RR", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060064"), name: "CyberCats", balance: BaseUnit(amount: 1, symbol: "CC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060065"), name: "FantasyFrogs", balance: BaseUnit(amount: 1, symbol: "FF", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060067"), name: "DigitalDinosaurs", balance: BaseUnit(amount: 1, symbol: "DINO", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060067"), name: "ArtificialAntelopes", balance: BaseUnit(amount: 1, symbol: "AA", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060068"), name: "PixelPenguins", balance: BaseUnit(amount: 1, symbol: "PE", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060069"), name: "NeonNarwhals", balance: BaseUnit(amount: 1, symbol: "NN", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060070"), name: "SiliconSeahorses", balance: BaseUnit(amount: 1, symbol: "SS", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060071"), name: "TechnoTurtles", balance: BaseUnit(amount: 1, symbol: "TT", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060072"), name: "LaserLlamas", balance: BaseUnit(amount: 1, symbol: "LL", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060073"), name: "QuantumKoalas", balance: BaseUnit(amount: 1, symbol: "QK", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060074"), name: "HolographicHippos", balance: BaseUnit(amount: 1, symbol: "HH", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060075"), name: "ElectricElephants", balance: BaseUnit(amount: 1, symbol: "EE", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060076"), name: "CyberCapybaras", balance: BaseUnit(amount: 1, symbol: "CB", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060077"), name: "DigitalDolphins", balance: BaseUnit(amount: 1, symbol: "DO", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060078"), name: "RoboticRaccoons", balance: BaseUnit(amount: 1, symbol: "RC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060079"), name: "VirtualVampires", balance: BaseUnit(amount: 1, symbol: "VM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060080"), name: "NeuralNetworkNinjas", balance: BaseUnit(amount: 1, symbol: "NNN", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060081"), name: "PixelPirates", balance: BaseUnit(amount: 1, symbol: "PI", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060082"), name: "CryptoCentaurs", balance: BaseUnit(amount: 1, symbol: "CT", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060083"), name: "SiliconSamurais", balance: BaseUnit(amount: 1, symbol: "SM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060084"), name: "DigitalDemons", balance: BaseUnit(amount: 1, symbol: "DM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060085"), name: "TechnoTitans", balance: BaseUnit(amount: 1, symbol: "TN", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060086"), name: "LaserLeprechauns", balance: BaseUnit(amount: 1, symbol: "LP", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060087"), name: "QuantumQueens", balance: BaseUnit(amount: 1, symbol: "QQ", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060088"), name: "AstroAntelopes", balance: BaseUnit(amount: 1, symbol: "AA", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060089"), name: "GalacticGiraffes", balance: BaseUnit(amount: 1, symbol: "GG", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060090"), name: "InterstellarIguanas", balance: BaseUnit(amount: 1, symbol: "II", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060091"), name: "NebulaNarwhals", balance: BaseUnit(amount: 1, symbol: "NN", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060092"), name: "OrbitingOwls", balance: BaseUnit(amount: 1, symbol: "OO", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060093"), name: "SpaceSharks", balance: BaseUnit(amount: 1, symbol: "SS", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060094"), name: "CosmicCheetahs", balance: BaseUnit(amount: 1, symbol: "CC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060095"), name: "CelestialCobras", balance: BaseUnit(amount: 1, symbol: "CLC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060096"), name: "GravityGorillas", balance: BaseUnit(amount: 1, symbol: "GG", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060097"), name: "MeteorMonkeys", balance: BaseUnit(amount: 1, symbol: "MM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060098"), name: "SupernovaSloths", balance: BaseUnit(amount: 1, symbol: "SN", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060099"), name: "StellarSeahorses", balance: BaseUnit(amount: 1, symbol: "SS", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060100"), name: "EclipseEagles", balance: BaseUnit(amount: 1, symbol: "EE", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060101"), name: "MoonbeamMeerkats", balance: BaseUnit(amount: 1, symbol: "MM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060102"), name: "AuroraAlligators", balance: BaseUnit(amount: 1, symbol: "AA", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060103"), name: "CometCougars", balance: BaseUnit(amount: 1, symbol: "CC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060104"), name: "QuasarQuokkas", balance: BaseUnit(amount: 1, symbol: "QQ", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060105"), name: "GalaxyGeckos", balance: BaseUnit(amount: 1, symbol: "GG", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060106"), name: "PulsarPandas", balance: BaseUnit(amount: 1, symbol: "PP", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060107"), name: "StarlightSquirrels", balance: BaseUnit(amount: 1, symbol: "SS", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060108"), name: "NebulaNewts", balance: BaseUnit(amount: 1, symbol: "NN", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060109"), name: "BlackHoleBunnies", balance: BaseUnit(amount: 1, symbol: "BH", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060110"), name: "CosmicCats", balance: BaseUnit(amount: 1, symbol: "CC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060111"), name: "AsteroidArmadillos", balance: BaseUnit(amount: 1, symbol: "AA", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060112"), name: "DwarfStarDolphins", balance: BaseUnit(amount: 1, symbol: "DS", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060113"), name: "CelestialChameleons", balance: BaseUnit(amount: 1, symbol: "CC", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060114"), name: "SpaceSnakes", balance: BaseUnit(amount: 1, symbol: "SS", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060115"), name: "MoonlitMoles", balance: BaseUnit(amount: 1, symbol: "MM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060116"), name: "WormholeWalruses", balance: BaseUnit(amount: 1, symbol: "WW", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060117"), name: "SolarSalamanders", balance: BaseUnit(amount: 1, symbol: "SS", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060118"), name: "InterstellarIguanas", balance: BaseUnit(amount: 1, symbol: "II", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060119"), name: "MarsMeerkats", balance: BaseUnit(amount: 1, symbol: "MM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060120"), name: "PlanetPenguins", balance: BaseUnit(amount: 1, symbol: "PP", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060121"), name: "SupernovaSloths", balance: BaseUnit(amount: 1, symbol: "SS", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060122"), name: "ExoplanetEagles", balance: BaseUnit(amount: 1, symbol: "EE", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060123"), name: "GalacticGiraffes", balance: BaseUnit(amount: 1, symbol: "GG", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060124"), name: "OrbitingOwls", balance: BaseUnit(amount: 1, symbol: "OO", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060125"), name: "SpaceWhales", balance: BaseUnit(amount: 1, symbol: "SW", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060126"), name: "LunarLlamas", balance: BaseUnit(amount: 1, symbol: "LL", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060127"), name: "RedDwarfRabbits", balance: BaseUnit(amount: 1, symbol: "RD", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060128"), name: "GravityGorillas", balance: BaseUnit(amount: 1, symbol: "GG", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060129"), name: "SatelliteSharks", balance: BaseUnit(amount: 1, symbol: "SS", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060130"), name: "MeteorMonkeys", balance: BaseUnit(amount: 1, symbol: "MM", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060131"), name: "AuroraAlligators", balance: BaseUnit(amount: 1, symbol: "AA", decimals: 0)),
		NonFungibleToken(id: AssetIdentifier(id: "060132"), name: "StellarStingrays", balance: BaseUnit(amount: 1, symbol: "SS", decimals: 0)),
	]
}
